### ISSUE TITLE
[Tracking] Hive test status [WIP]

### ISSUE THREAD

**Issue by fmoletta** [lambdaclass/ethereum_rust#262]
# Hive Testing Status
### eth_getStorageAt
- [ ]   get-storage-invalid-key-too-large #256  + #261 
- [ ] get-storage-invalid-key  #256  + #261 
- [ ] get-storage-unknown-account  #256 + #259 + #260
- [ ] get-storage #256 + #260 
### eth_blockNumber
- [ ]   simple-test #255 
### eth_chainId
- [x]   get-chain-id
### eth_createAccessList
- [ ]   create-al-contract-eip1559
- [ ]   create-al-contract
- [ ]   create-al-value-transfer
### eth_getBlockByHash
- [x]   get-block-by-empty-hash
- [ ]   get-block-by-hash
- [x]   get-block-by-notfound-hash
### eth_getBlockByNumber
- [ ]   get-block-n
- [ ]   get-block-notfound
- [ ]   get-finalized
- [ ]   get-genesis
- [ ]   get-latest
- [ ]   get-safe
### eth_getBlockReceipts
- [ ]   get-block-receipts-0
- [ ]   get-block-receipts-by-hash
- [ ]   get-block-receipts-earliest
- [ ]   get-block-receipts-empty
- [ ]   get-block-receipts-future
- [ ]   get-block-receipts-latest
- [ ]   get-block-receipts-n
- [ ]   get-block-receipts-not-found
### eth_getBalance
- [ ]  get-balance-blockhash
- [ ]  get-balance-unknown-account #256 + #259 
- [ ]  get-balance #258 
### eth_getCode
- [ ]   get-code-unknown-account #256 + #259 
- [ ]   get-code #258 
### eth_getTransactionByBlockHashAndIndex
- [ ]   get-block-n
### eth_getTransactionByHash
- [ ]   get-access-list
- [ ]   get-blob-tx
- [ ]   get-dynamic-fee
- [ ]   get-empty-tx
- [ ]   get-legacy-create
- [ ]   get-legacy-input
- [ ]   get-legacy-tx
- [ ]   get-notfound-tx
### eth_getTransactionReceipt
- [ ]   get-access-list
- [ ]   get-blob-tx
- [ ]   get-dynamic-fee
- [ ]   get-empty-tx
- [ ]   get-legacy-contract
- [ ]   get-legacy-input
- [ ]   get-legacy-receipt
- [ ]   get-notfound-tx
### debug_getRawBlock
- [ ]   get-block-n
- [ ]   get-genesis
- [ ]   get-invalid-number
### debug_getRawHeader
- [ ]   get-block-n
- [ ]   get-genesis
- [ ]   get-invalid-number
### debug_getRawReceipts
- [ ]   get-block-n
- [ ]   get-genesis
- [ ]   get-invalid-number
### debug_getRawTransaction
- [ ]   get-invalid-hash
- [ ]   get-tx
### eth_blobGasPrice
- [ ]   blob-gas-price
### eth_call
- [ ]   call-callenv-options-eip1559
- [ ]   call-callenv
- [ ]   call-contract
- [ ]   call-revert-abi-error
- [ ]   call-revert-abi-panic
### eth_estimateGas
- [ ]   estimate-failed-call
- [ ]   estimate-simple-transfer
- [ ]   estimate-successful-call
### eth_feeHistory
- [ ]   fee-history
### eth_getLogs
- [ ]   contract-addr
- [ ]   no-topics
- [ ]   topic-exact-match
- [ ]   topic-wildcard
### eth_getProof
- [ ]   get-account-proof-blockhash
- [ ]   get-account-proof-latest
- [ ]   get-account-proof-with-storage
### eth_getBlockTransactionCountByHash
- [ ]   get-block-n
- [ ]   get-genesis
### eth_getBlockTransactionCountByNumber
- [ ]   get-block-n
- [ ]   get-genesis
### eth_getTransactionCount
- [ ]   get-nonce-unknown-account
- [ ]   get-nonce
### eth_sendRawTransaction
- [ ] send-access-list-transaction
- [ ]   send-blob-tx
- [ ]   send-dynamic-fee-access-list-transaction
- [ ]   send-dynamic-fee-transaction
- [ ]   send-legacy-transaction
### eth_syncing
- [ ]   check-syncing

**Comment by fmoletta** [comment]
Deprecated in favor of #264

**Comment by fmoletta** [comment]
Deprecated in favour of https://github.com/lambdaclass/ethereum_rust/issues/264
