### ISSUE TITLE
feat(evm-mlir): [Tracking] Ethereum Foundation tests

### ISSUE THREAD

**Issue by lazcanoluca** [lambdaclass/ethereum_rust#668]
📂  **General State Tests**
- [x] Cancun/stEIP1153-transientStorage
- [ ] Cancun/stEIP4844-blobtransactions lambdaclass/ethereum_rust#617 
- [ ] lambdaclass/ethereum_rust#609
- [x] Pyspecs/berlin/eip2930_access_list
- [x] lambdaclass/ethereum_rust#608
- [ ] Pyspecs/cancun/eip1153_tstore
- [ ] Pyspecs/cancun/eip4844_blobs lambdaclass/ethereum_rust#617 
- [ ] Pyspecs/cancun/eip5656_mcopy
- [ ] Pyspecs/cancun/eip6780_selfdestruct
- [x] Pyspecs/cancun/eip7516_blobgasfee
- [ ] Pyspecs/frontier/opcodes
- [ ] Pyspecs/homestead/yul
- [x] Pyspecs/istanbul/eip1344_chainid
- [x] Pyspecs/shanghai/eip3651_warm_coinbase
- [ ] Pyspecs/shanghai/eip3855_push0
- [ ] Pyspecs/shanghai/eip3860_initcode
- [ ] VMTests/vmArithmeticTest
- [x] VMTests/vmBitwiseLogicOperation
- [ ] VMTests/vmIOandFlowOperations
- [ ] VMTests/vmLogTest
- [x] VMTests/vmPerformance
- [ ] VMTests/vmTests
- [x] stArgsZeroOneBalance
- [ ] stAttackTest
- [ ] lambdaclass/ethereum_rust#564
- [x] stBugs
- [ ] stCallCodes
- [ ] stCallCreateCallCodeTest
- [x] stCallDelegateCodesCallCodeHomestead
- [x] stCallDelegateCodesHomestead
- [x] stChainId
- [ ] stCodeCopyTest
- [x] stCodeSizeLimit
- [ ] stCreate2 lambdaclass/evm_mlir#405 
- [ ] stCreateTest lambdaclass/evm_mlir#402 
- [ ] stDelegatecallTestHomestead
- [ ] stEIP150Specific
- [ ] stEIP150singleCodeGasPrices
- [ ] stEIP1559
- [x] stEIP158Specific
- [x] stEIP2930
- [ ] stEIP3607
- [ ] stExample
- [ ] stExtCodeHash
- [ ] stHomesteadSpecific
- [ ] stInitCodeTest
- [ ] stLogTests
- [ ] stMemExpandingEIP150Calls
- [ ] stMemoryStressTest
- [ ] stMemoryTest
- [ ] stNonZeroCallsTest
- [x] lambdaclass/evm_mlir#431
- [x] lambdaclass/evm_mlir#448
- [ ] stQuadraticComplexityTest
- [ ] stRandom lambdaclass/evm_mlir#412 
- [ ] stRandom2 lambdaclass/evm_mlir#412 
- [ ] stRecursiveCreate lambdaclass/evm_mlir#395 
- [x] stRefundTest
- [ ] stReturnDataTest
- [ ] stRevertTest
- [x] stSLoadTest
- [x] stSStoreTest
- [ ] stSelfBalance
- [x] stShift
- [ ] stSolidityTest
- [ ] stSpecialTest
- [ ] stStackTests
- [ ] stStaticCall
- [x] stStaticFlagEnabled
- [ ] stSystemOperationsTest
- [ ] stTimeConsuming
- [ ] stTransactionTest
- [x] stTransitionTest
- [x] stWalletTest
- [x] stZeroCallsRevert
- [ ] stZeroCallsTest
- [ ] stZeroKnowledge
- [ ] stZeroKnowledge2
