### ISSUE TITLE
feat(evm-mlir): [Tracking] Implement precompiles

### ISSUE THREAD

**Issue by MegaRedHand** [lambdaclass/ethereum_rust#669]
Precompiles are special addresses which execute precompiled logic instead of internal transactions. A list can be found in [evm.codes/precompiled](https://www.evm.codes/precompiled)

- [x] lambdaclass/evm_mlir#338
- [x] lambdaclass/evm_mlir#339
- [x] lambdaclass/evm_mlir#340
- [x] lambdaclass/evm_mlir#341
- [x] lambdaclass/evm_mlir#342
- [x] lambdaclass/evm_mlir#343
- [x] lambdaclass/evm_mlir#344
- [x] lambdaclass/evm_mlir#345
- [x] lambdaclass/evm_mlir#346
- [ ] lambdaclass/ethereum_rust#637
